### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by Jay1508** [Bert-JanP/Incident-Response-Powershell#10]
Hi Bert-Jan,

I apologize for reaching out through this platform, as I encountered difficulty contacting you directly on LinkedIn without a premium account.

Upon utilizing the DFIR script in my environment, I identified areas for potential enhancement, despite its already great functionality.

1. Compress-Archive limitations. This cmdlet can only create archive of 2GB max, alternatively you can use the .NET System.IO.Compression.ZipFile class directly. This will allow you to compress a folder larger than 2GB:

# Load the assembly containing the ZipFile class
Add-Type -AssemblyName System.IO.Compression.FileSystem
# Compress the folder to a zip file
[System.IO.Compression.ZipFile]::CreateFromDirectory($sourceFolderPath, $destinationZipPath)

2. Create a new function to collect the Powershell console history of ALL users (domain and local) that logged on the compromised workstation/server. Below is the new function that you could use to achieve this:

function Get-PowershellConsoleHistory-AllUsers {
    Write-Host "Collection Console Powershell History..."
    $PowershellConsoleHistory = "$FolderCreation\ConsolePowershellHistory"
    mkdir -Force $PowershellConsoleHistory | Out-Null
    # Specify the directory where user profiles are stored
    $usersDirectory = "C:\Users"

    # Get a list of all user directories in C:\Users
    $userDirectories = Get-ChildItem -Path $usersDirectory -Directory
    foreach ($userDir in $userDirectories) {
        $userName = $userDir.Name
        $historyFilePath = Join-Path -Path $userDir.FullName -ChildPath "AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt"
        if (Test-Path -Path $historyFilePath -PathType Leaf) {
            $outputDirectory = "$PowershellConsoleHistory\$userDir.Name"
            mkdir -Force $outputDirectory | Out-Null
            Copy-Item -Path $historyFilePath -Destination $outputDirectory -Force
        }
    }    
}

3. Only collect the .log files from the MPLogs folder. The MPLogs folder seems to contain various type of files (eg .bin, .log). As an incident responder, I think the only valuable information are the .logs files. I re-wrote the function Get-MPLogs to only collect the .log files:

function Get-MPLogs {
	Write-Host "Collecting MPLogs..."
	$MPLogFolder = "$FolderCreation\MPLogs"
	New-Item -Path $MPLogFolder -ItemType Directory -Force | Out-Null
	$MPLogLocation = "C:\ProgramData\Microsoft\Windows Defender\Support"
    $MPListFiles = Get-ChildItem -Path $MPLogLocation -Name "*.log"
    foreach ($file in $MPListFiles){
        Copy-Item -Path $MPLogLocation\$file -Destination $MPLogFolder
    }
}

4. Delete the original folder upon completion of the archive. The evidence collected can be relatively large (depending on the environment) so I'd suggest to remove the original folder in the Zip-Results function.

Remove-Item -Path $FolderCreation -Recurse

Hope you find this useful
Jamal
Linkedin: https://www.linkedin.com/in/jamal-lalaoui-695a8624/

**Comment by Bert-JanP** [comment]
Hi Jamal,

Thank you for listing the improvements! I will have a better look in the upcoming week(s). Really appreciate the feedback.

Bert-Jan

**Comment by Bert-JanP** [comment]
The last two additions are implemented in version DFIR PowerShell V2.1.0.
