### ISSUE TITLE
Scheduled Tasks Section

### ISSUE THREAD

**Issue by colesmith2344** [Bert-JanP/Incident-Response-Powershell#12]
Ive been working on editing the script to try and have less noise in the scheduled task section. My idea is to only pull newly created or modified within the last 7 days. However, I can't seem to get it to see anything when it runs although I know I created a new reg key right before I tried. Does the below function that I modified make any sense or am I banging my head against a wall? 

function Get-ScheduledTasks {
    Write-Host "Collecting Scheduled Tasks..."
    $ScheduledTaskFolder = "$FolderCreation\ScheduledTask"
    mkdir -Force $ScheduledTaskFolder| Out-Null
    $daysAgo = (Get-Date).AddDays(-7)
    $ProcessOutput = "$ScheduledTaskFolder\ScheduledTasksList.txt"
    Get-ScheduledTask | Where-Object { ($_.LastRunTime -ge $daysAgo) -or ($_.NextRunTime -ge $daysAgo) } | Format-List | Out-File -Force -FilePath $ProcessOutput
}

**Comment by colesmith2344** [comment]
I also tried to use the $sw parameter but make me put in the value of it even though it should be pointing back to the value of two the others. 

function Get-ScheduledTasks {
    param(
        [Parameter(Mandatory=$true)][String]$sw
    )
    Write-Host "Collecting Scheduled Tasks..."
    $ScheduledTaskFolder = "$FolderCreation\ScheduledTask"
    mkdir -Force $ScheduledTaskFolder| Out-Null
    $ProcessOutput = "$ScheduledTaskFolder\ScheduledTasksList.txt"
    Get-ScheduledTask -After (Get-Date).AddDays(-$sw) | Where-Object {$_.State -ne "Disabled"} | Format-List | Out-File -Force -FilePath $ProcessOutput
}

**Comment by Bert-JanP** [comment]
Hey, 

This took way too long to investigate. I added your suggestion now as a default value, the scheduled task should have been executed in the last 7 days, or the LastRunTime must be empty to show up in the logs.

```Powershell
Get-ScheduledTask | Where-Object {($_.State -ne 'Disabled') -and (($_.LastRunTime -eq $null) -or ($_.LastRunTime -gt (Get-Date).AddDays(-7)))}
```
