### ISSUE TITLE
Issues with Get-EVTXFiles

### ISSUE THREAD

**Issue by dumforms** [Bert-JanP/Incident-Response-Powershell#6]
The function Get-EVTXFiles always results in errors because the foreach loop attempts to copy items from `$($EventViewer)\$($channel).evtx`. This path does not exist at the time it is called (it is supposed to be the destination path). The function should copy from `$($evtxPath)\$($channel).evtx` instead.

I also recommend changing the `$EventViewer` path from `$FolderCreation\Event Viewer` to `$FolderCreation\EventViewer` to be consistent with the other folder names (SecurityEvents, ProcessInformation, etc.).

**Comment by Bert-JanP** [comment]
Thanks! Will have a look at it together with the PR that's currently open.

**Comment by Bert-JanP** [comment]
Issue is fixed in Update DFIR-Script.ps1 #5
