### ISSUE TITLE
Version posted in Releases

### ISSUE THREAD

**Issue by lnk-0** [Bert-JanP/Incident-Response-Powershell#8]
Hi,

The version posted under "Releases" contains what appears to be your test output path. 

Line 65 - $FolderCreation = "D:\Github\DFIR-$env:computername-$ExecutionTime"

Commented out below on Line 66 looks to be the intended output directory. Code posted on the main page appears to be fine (https://github.com/Bert-JanP/Incident-Response-Powershell/blob/main/DFIR-Script.ps1).

**Comment by Bert-JanP** [comment]
Thanks for mentioning, I have just pushed a new release which uses the already updated PowerShell file you mentioned.
